CBVsProject/CBVsProject/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls', namespace = 'basic_app') )
]

CBVsProject/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(),name='list'),
    path('<int:pk>',views.SchoolDetailView.as_view(),name='detail'),
    path('<slug:pk>',views.SchoolDetailView.as_view(),name='detail'),
    path('create/', views.SchoolCreateView.as_view(),name = 'create'), 
    path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete'),

]

CBVsProject/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class School(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)


    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("basic_app:list") 



class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete='DO_NOTHING')

    def __str__(self):
        return self.name

CBVsProject/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,TemplateView,
                                    ListView,DetailView,
                                    CreateView,UpdateView,
                                    DeleteView)  
# Create your views here.
from . import models
from django.urls import reverse_lazy

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School



class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_details.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School
    template_name = 'basic_app/school_form.html'

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    template_name = 'school_conf_delete.html'
    success_url = reverse_lazy('basic_app:list')

CBVsProject/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{%url 'basic_app:list' %}">SCHOOLS</a>
        <ul class="navbar-nav mr-auto">
            <!-- <li> </li> -->
            <li class="nav-item active"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a></li>
            <li><a href=""></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block bodyblock %}

        {% endblock %}
        
    </div>
    
</body>
</html>

CBVsProject/basic_app/templates/basic_app/school_details.html
{% extends 'basic_app/basic_app_base.html' %}

{% block bodyblock %}

<div class="jumbotron">
    <h1>Welcome to School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>location: {{school_detail.location}}</p>

    <h2>Students:</h2>
    {% for student in school_detail.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
    <p><a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>

</div>
    

</div>

{% endblock %}

CBVsProject/basic_app/templates/basic_app/school_form.html
{%extends "basic_app/basic_app_base.html" %}

{% block bodyblock %}


<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class="btn btn-primary" value="submit">
    </form>



{% endblock %}

CBVsProject/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}

{% block bodyblock %}

    <div class="jumbotron">
        <h1>Welcome to a list of all the schools!!</h1>
    <ol>
        {% for school in schools %}
        <h2><li><a class="active-link" style="color: black;" href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor %}
    </ol>

    <p><a class="btn btn-primary" href="{% url 'basic_app:create' %}">Create</a></p>

    </div>
{% endblock %}

CBVsProject/basic_app/templates/school_conf_delete.html
{% extends 'basic_app/basic_app_base.html' %}

{% block bodyblock %}

<h2>Delete {{school.name}}??</h2>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
</form>
{% endblock %}

CBVsProject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li> <a class="navbar-brand" href="{%url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href=""></a></li>
        </ul>
    </nav>
    <div class="container">
        {% block bodyblock %}

        {% endblock %}
        
    </div>
    
</body>
</html>

CBVsProject/templates/index.html
{% extends 'base.html' %}
{% block bodyblock %}
   <div class="jumbotron">
    <h1>HOMEPAGE    </h1>
   </div>
{% endblock %}